module.exports = {
    USER_CTR_MSG: {
      ALL_FIELDS_ARE_REQUIRED: "All fields are required.",
      EMAIL_ALREADY_EXISTS: "Email already exists.",
      USER_CREATED_SUCCESSFULLY: "Sign-Up Successfull!.",
      USER_NOT_FOUND: "User not found.",
      USER_UPDATED_SUCCESSFULLY: "User updated successfully.",
      USER_DELETED_SUCCESSFULLY: "User deleted successfully.",
      INVALID_DATA: "Invalid data provided.",
      DUPLICATE_EMAIL: "Duplicate email address.",
      FETCH_USERS_SUCCESS: "Fetched all users successfully.",
      FETCH_USER_SUCCESS: "Fetched user by ID successfully.",
      ERROR_CREATING_USER: "An error occurred while creating the user.",
      ERROR_FETCHING_USERS: "An error occurred while fetching users.",
      ERROR_FETCHING_USER: "An error occurred while fetching the user.",
      ERROR_UPDATING_USER: "An error occurred while updating the user.",
      ERROR_DELETING_USER: "An error occurred while deleting the user.",
    },
    REVIEW_CTR_MSG: {
      INVALID_REVIEW_ID: "Invalid review ID.",
      REVIEW_NOT_FOUND: "Review not found.",
      COMMENT_TOO_SHORT: "Comment should be at least 10 characters long.",
      REVIEW_CREATED_SUCCESSFULLY: "Review created successfully.",
      REVIEW_UPDATED_SUCCESSFULLY: "Review updated successfully.",
      REVIEW_DELETED_SUCCESSFULLY: "Review deleted successfully.",
      INVALID_RATER: "Invalid rater ID.",
      INVALID_COURSE: "Invalid course ID.",
      RATING_OUT_OF_BOUNDS: "Rating must be between 1 and 5.",
      RATING_CREATED_SUCCESSFULLY: "Rating created successfully.",
      RATING_UPDATED_SUCCESSFULLY: "Rating updated successfully.",
      RATING_DELETED_SUCCESSFULLY: "Rating deleted successfully.",
      INTERNAL_SERVER_ERROR: "Internal Server Error",
    },
    MESSAGES: {
      USER_NOT_FOUND: "User not found",
      COURSE_NOT_FOUND: "Course not found",
      PAYMENT_ORDER_ERROR: "Error creating payment order",
      PAYMENT_VERIFIED_SUCCESS: "Payment verified successfully",
      PAYMENT_VERIFICATION_FAILED: "Payment verification failed with status: ",
      PAYMENT_FAILED: "Payment verification failed due to invalid response",
      INTERNAL_SERVER_ERROR: "Internal server error",
      MODULE_CREATED: "Module created successfully and added to course.",
      MODULE_UPDATED: "Module updated successfully.",
      MODULE_DELETED: "Module deleted successfully.",
      MODULE_NOT_FOUND: "Module not found.",
      INVALID_COURSE_ID: "Invalid course_id. Course does not exist.",
      ERROR_CREATING_MODULE: "Error creating module:",
      ERROR_FETCHING_MODULES: "Error fetching modules:",
      ERROR_FETCHING_MODULE_BY_ID: "Error fetching module by ID:",
      ERROR_UPDATING_MODULE: "Error updating module:",
      ERROR_DELETING_MODULE: "Error deleting module:",
    },
  
    ERRORS: {
      PAYMENT_ERROR: "Error verifying payment",
      INTERNAL_SERVER: "An internal server error occurred.",
    },
    COMMON_MSG: {
      INSTRUCTOR_CREATED: "Instructor created successfully",
      INSTRUCTOR_FETCHED: "Instructor fetched successfully",
      INSTRUCTORS_FETCHED: "Instructors fetched successfully",
      INSTRUCTOR_NOT_FOUND: "Instructor not found",
      INSTRUCTOR_UPDATED: "Instructor updated successfully",
      INSTRUCTOR_DELETED: "Instructor deleted successfully",
      REQUIRED_FIELDS_MISSING: "All required fields must be provided",
      ERROR_CREATING_INSTRUCTOR:
        "An error occurred while creating the instructor",
      ERROR_FETCHING_INSTRUCTORS: "An error occurred while fetching instructors",
      ERROR_FETCHING_INSTRUCTOR:
        "An error occurred while fetching the instructor",
      ERROR_UPDATING_INSTRUCTOR:
        "An error occurred while updating the instructor",
      ERROR_DELETING_INSTRUCTOR:
        "An error occurred while deleting the instructor",
      REQUIRED_FIELDS_MISSING: "All required fields must be provided",
      INVALID_OR_EXPIRED_OTP: "Invalid or expired OTP",
      OTP_EXPIRED: "OTP has expired. Please request a new one.",
      OTP_VERIFIED: "OTP verified successfully",
      USER_NOT_FOUND: "User not found",
      PASSWORD_UPDATED: "Password updated successfully",
      ERROR_SENDING_OTP: "Error sending OTP email",
      ERROR_UPDATING_PASSWORD: "Error updating password",
      REQUIRED_FIELDS_MISSING: "All required fields must be provided",
      INSTRUCTOR_NOT_FOUND: "Instructor not found",
      INVALID_INSTRUCTOR_ID: "Invalid instructor ID format",
      LANGUAGE_VALIDATION_ERROR:
        "Language must be an array containing valid languages",
      LEVEL_VALIDATION_ERROR: "Level must be an array containing valid levels",
      REQUIREMENTS_VALIDATION_ERROR: "Requirements must be an array of strings",
      TARGET_AUDIENCE_VALIDATION_ERROR:
        "Target audience must be an array of strings",
      COURSE_OUTCOMES_VALIDATION_ERROR:
        "Learning outcomes must be an array of strings",
      COURSE_CREATED_SUCCESS: "Course created successfully",
      COURSE_FETCHED_SUCCESS: "Courses fetched successfully",
      COURSE_NOT_FOUND: "Course not found",
      COURSE_UPDATED_SUCCESS: "Course updated successfully",
      COURSE_DELETED_SUCCESS: "Course deleted successfully",
      THUMBNAIL_UPDATED_SUCCESS: "Thumbnail updated successfully",
      ERROR_CREATING_COURSE: "An error occurred while creating the course",
      ERROR_FETCHING_COURSES: "An error occurred while fetching courses",
      ERROR_UPDATING_COURSE: "An error occurred while updating the course",
      ERROR_DELETING_COURSE: "An error occurred while deleting the course",
      ERROR_UPDATING_THUMBNAIL: "Error updating thumbnail",
    },
    ADVERTISEMENT_MESSAGES: {
      NO_FILE_UPLOADED: "No file uploaded",
      AD_CREATED_SUCCESS: "Advertisement created successfully",
      AD_FETCHED_SUCCESS: "Advertisement fetched successfully",
      AD_NOT_FOUND: "Advertisement not found",
      ERROR_CREATING_AD: "Error uploading advertisement image",
      ERROR_FETCHING_AD: "Error fetching advertisement",
      ERROR_UPDATING_AD: "Error updating ad",
      ERROR_DELETING_AD: "Error deleting ad",
    },
    ADMIN_MESSAGES: {
      EMAIL_REQUIRED: "Email and Name are required",
      EMAIL_IN_USE: "Email is already in use",
      INVALID_COURSE_ID: "One or more course IDs are invalid",
      PASSWORD_REQUIRED: "Password is required",
      ADMIN_CREATED_SUCCESS: "Admin created successfully",
      ADMIN_NOT_FOUND: "Admin not found",
      ADMIN_UPDATED_SUCCESS: "Admin updated successfully",
      ADMIN_DELETED_SUCCESS: "Admin deleted successfully",
      ERROR_CREATING_ADMIN: "An error occurred while creating the admin",
      ERROR_FETCHING_ADMINS: "An error occurred while fetching admins",
      ERROR_FETCHING_ADMIN: "An error occurred while fetching the admin",
      ERROR_UPDATING_ADMIN: "An error occurred while updating the admin",
      ERROR_DELETING_ADMIN: "An error occurred while deleting the admin",
    },
  };
  